name: Arachni Scan

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  dast_scan:
    name: DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Arachni
        run: |
          wget https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
          tar -xzf arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
          cd arachni-1.5.1-0.5.12/bin
          ./arachni http://www.example.com --report-save-path=arachni_report.afr

      - name: Upload Arachni Report
        uses: actions/upload-artifact@v2
        with:
          name: arachni-report
          path: arachni_report.afr

