name: Arachni Scan

on:
  workflow_dispatch:
  workflow_call:

jobs:
  arachni_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Arachni
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential libsqlite3-dev ruby-dev
        gem install bundler
        git clone --depth 1 https://github.com/Arachni/arachni.git
        cd arachni
        bundle install --without profiling development
        echo "Arachni installed successfully"

    - name: Run Arachni Scan
      run: |
        cd arachni
        ./bin/arachni http://testphp.vulnweb.com/ --report-save-path=arachni_report.afr

    - name: Upload Arachni Report
      uses: actions/upload-artifact@v2
      with:
        name: arachni_report
        path: arachni/arachni_report.afr

      - name: Upload zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: arachni-report
          path: $GITHUB_WORKSPACE/arachni_report.zip
