name: Arachni DAST Scan

on:
  push:
    branches:
      - main  # Adjust this according to your main branch name
  pull_request:
    branches:
      - main  # Adjust this according to your main branch name

jobs:
  arachni_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Arachni Scan
      run: |
        docker run --rm -v $(pwd):/home/arachni/arachni_reports hakiri/arachni arachni http://tesphp.vulnweb.com/ --report-save-path=/home/arachni/arachni_reports/arachni_report.afr

    - name: Upload Arachni Report
      uses: actions/upload-artifact@v2
      with:
        name: arachni_report
        path: arachni_reports/arachni_report.afr
