name: Arachni Scan

on:
  workflow_dispatch:
  workflow_call:

jobs:
  arachni-scan:
    name: Arachni
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Arachni Docker image
        run: docker pull arachni/arachni

      - name: Run Arachni scan
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/home/arachni/reports arachni/arachni http://testphp.vulnweb.com/ --report=arachni_report.afr

      - name: Convert .afr to HTML
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/home/arachni/reports arachni/arachni_reporter -f html /home/arachni/reports/arachni_report.afr
          mv arachni_report.html $GITHUB_WORKSPACE/arachni_report.html

      - name: Package HTML report into zip
        run: |
          zip -r $GITHUB_WORKSPACE/arachni_report.zip $GITHUB_WORKSPACE/arachni_report.html $GITHUB_WORKSPACE/arachni_report.afr

      - name: Upload zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: arachni-report
          path: $GITHUB_WORKSPACE/arachni_report.zip
