name: Arachni Scan

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Archani-scan:
    name: Arachani
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Arachni
        run: |
          wget https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
          tar -xzf arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
          cd arachni-1.5.1-0.5.12/bin
          ./arachni https://testphp.vulnweb.com/ --report ./.github arachni_report.afr

      - name: Convert .afr to HTML
        run: |
          ./.github/arachni_reporter -f html $GITHUB_WORKSPACE/arachni_report.afr
          mv arachni_report.html $GITHUB_WORKSPACE/arachni_report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: arachni-report
          path: $GITHUB_WORKSPACE/arachni_report.html

