name: 50 DAST Scan Docker Image
on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true

  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true
env:
# used for docker
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ inputs.image-tag || github.event.inputs.image-tag }}
jobs:
  dast-scan:
    name: DAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP OWASP full scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-a -j -l WARN -z "-addoninstallall" '
          allow_issue_writing: true
        id: zap-scan
